[build-system]
requires = ["hatchling", "hatch-requirements-txt", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "astrophot"
dynamic = ["version"]
authors = [
  { name="Connor Stone", email="connorstone628@gmail.com" },
]
description = "A fast, flexible, full featured, and differentiable astronomical image 2D forward modelling tool for precise parallel multi-wavelength photometry."
readme = "README.md"
requires-python = ">=3.11"
license = {file = "LICENSE"}
keywords = [
        "astrophot",
        "photometry",
        "astronomy",
        "scientific computing",
        "astrophysics",
        "differentiable programming",
        "pytorch",
        "jax",
        "bayesian inference",
]
classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3"
]
dependencies=[
        "astropy>=6.0",
        "caskade>=0.15.0,<1.2.0",
        "h5py>=3.8.0",
        "matplotlib>=3.7",
        "numpy>=1.24.0,<3",
        "scipy>=1.10.0",
        "torch>=2.0.0",
        "tqdm>=4.65.0",
]

[project.urls]
Homepage = "https://autostronomy.github.io/AstroPhot/"
Documentation = "https://autostronomy.github.io/AstroPhot/"
Repository = "https://github.com/Autostronomy/AstroPhot"
Issues = "https://github.com/Autostronomy/AstroPhot/issues"

[project.optional-dependencies]
dev = [
        "pre-commit",
        "nbval",
        "nbconvert",
        "graphviz",
        "ipywidgets",
        "jupyter-book<2.0",
        "matplotlib",
        "photutils",
        "scikit-image",
        "caustics>=1.6.0",
        "pyro-ppl>=1.8.0",
        "emcee",
        "corner",
        "jax>=0.8.0",
        "pyvo"
]

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "astrophot/_version.py"

[tool.hatch.version.raw-options]
local_scheme = "no-local-version"
