sphinx:
  extra_extensions:
    - "sphinx.ext.autodoc"
    - "sphinx.ext.autosummary"
    - "sphinx.ext.viewcode"
    - "sphinx.ext.mathjax"
  config:
    html_theme_options:
      logo:
        image_light: ../../media/AP_logo.png
        image_dark: ../../media/AP_logo_white.png
    autodoc_default_options:
      members: true
      undoc-members: true
      show-inheritance: true
